
<html>
<head>
<title>March, 2005: Resource  Management in Python</title>
</head>

<body BGCOLOR="#ffffff" LINK="#0000ff" VLINK="#330066" ALINK="#ff0000" TEXT="#000000">
<!--Copyright &#169; Dr. Dobb's Journal-->

<h1>Resource  Management in Python</h1>
<p><i>Dr. Dobb's Journal</i> March, 2005</p>
<h2>When portability, robustness, and performance are important</h2>


<h3>By Oliver Schoenborn</h3>


<I>Oliver is a researcher for the National Research Council of Canada doing R&amp;D in simulation systems for engineering applications in virtual reality. He can be contacted at oliver.schoenborn@utoronto.ca.</I>

<hr>





<p>A resource is something that is useful and in limited supply. This includes everything from computer memory and disk space, to filehandles/sockets and threads, mutexes, and semaphores. It is therefore important that resources be returned to the system when they are no longer in use. Failure to do so eventually results in poor performance and ultimately in "starvation"&#151;insufficient memory for the next operation, insufficient disk space, inability to create new threads, and the like. More often, however, it leads to nasty bugs, such as lost data and deadlocks.</p>

<p>Python does a good job of making resource management almost trivial. However, there are some important subtleties that can have a serious effect on the portability, robustness, performance, or even correctness of your Python programs. In this article, I discuss those subtleties and some of the modules and techniques you can use to get around them.</p>

<p>In Python, resources are not available directly but are wrapped in higher level Python objects that you instantiate and use in your own Python objects and functions. Resource management consists of the tasks that you and/or the Python interpreter must carry out to ensure that a resource that you have acquired is returned to the system. </p>

<p>There are actually three issues that may not be immediately apparent to you in Python's resource management model:</p>



<ul>
  <li>NonDeterministic destruction (NDD).</li>
  <li>Circular references.</li>
  <li>Uncaught exceptions.</li>
</ul>
<h3>NDD</h3>

<p>Resource management in Python is trivial 90 percent of the time because it is automated: Once you no longer need an object (say after you return from a function), you can just forget about it, and the interpreter does its best to eventually release it. </p>

<p>The "eventually" part of this statement refers to the fact that the Python Language Reference Manual (http://docs.python .org/ref/ref.html) guarantees that objects stay alive as long as they are in use. This means that if you create an object <i>foo</i> in a function <i>A</i> and from there call another function <i>B</i> that creates a global reference to <i>foo</i>, <i>foo</i> stays alive past the return from function <i>A</i>, at least until that global reference is discarded. There is, therefore, no way for you to know when your object will no longer be in use. </p>

<p>The "its best" refers to the fact that the Python Language Reference (PLR) does not prescribe what the interpreter must do with <i>foo</i> once there are no other objects left referring to it; for instance, after <i>foo</i> has become unreachable or "garbage." Actually, the PLR does not even prescribe that the interpreter must notice at all. Many languages have that as well, Java and C# being two such examples. Therefore, "its best" depends on the interpreter implementation; CPython, Jython, and IronPython are the most well known. This indeterminism is a trap that is difficult for newcomers to Python to discern because of the <i>del</i> operator and <i>__del__</i> class method. The <i>del</i> operator simply removes a variable name from the local or global namespace, it says nothing about object destruction. On the other hand, the <i>__del__</i> method is called automatically by the interpreter just before the object is destroyed. But as explained earlier, object destruction is not guaranteed to occur. The call to your object's <i>__del__</i> is completely out of your control and may never happen, and using the <i>del</i> operator will not help. The only reliable use for the <i>del</i> operator is to make sure you (or a user of your module) can't mistakenly use a name that shouldn't be used. </p>

<p>This can be even harder to accept for many Pythoneers who only have experience with the CPython implementation: That implementation appears deterministic because in trivial examples such as <i>a = foo(); del a</i>, the <i>foo</i> is immediately destroyed. Consequently, you may not realize that your code will not work with other interpreter implementations.</p>

<p>This indeterminism is even a trap for experienced programmers who have a background in object-oriented languages that have deterministic destruction (such as C++), where create-release pairs (for instance, the "resource acquisition is initialization," or "RAII" idiom) are used heavily, and to great effect. It is tempting to see <i>del</i> as the equivalent of <i>delete</i>, and <i>__del__</i> as equivalent to a destructor. The two statements taken separately are true, but the difference from C++ is that Python's  "delete" does not call the "destructor." </p>

<p>In fact, <i>__del__</i> is not only effectively useless for lifetime management, but should be avoided due to reference cycles. </p>
<h3>Circular References</h3>

<p>In Python, variable names are references to objects, not objects in and of themselves. A Python interpreter tracks whether an object is in use by how many variable names refer to that object&#151;its "reference count" (which, in the CPython implementation of Python, would be the same as returned by <i>sys.getrefcount(obj)</i>). Unfortunately, even if the PLR prescribed that objects <i>shall</i> be destroyed, and subjected to this <i>as soon as</i> they are no longer referenced by any variable names, you wouldn't be much further ahead because of reference cycles. A reference cycle occurs when an object directly or indirectly refers to itself. For instance, <a name="rl1"></a><a href="#l1">Listing One</a> leads an <i>A (aa)</i> to refer to a <i>B (aa.b)</i>, which in turn refers to <i>aa</i> via <i>aa.b.a</i>, and <i>aa</i> -&gt; <i>aa.b</i> -&gt; <i>aa</i>, thus creating a reference cycle. </p>

<p>Reference cycles are more common than you might think. For example, they are common in GUI libraries, where information must flow up/down GUI component trees. </p>

<p>While reference cycles are not a problem per se, they do prevent the reference count of all objects in the cycle from going to zero&#151;even those not directly in the chain. So, those objects are never destroyed and associated resources are never released. Hence, reference cycles are a problem only when there are critical resources to release; for example, mutex locks, opened files, and the like, or if cycles get continuously created (as in a loop), which leads to an ever-increasing memory consumption of your program (<a name="rl2"></a><a href="#l2">Listing Two</a>).</p>

<p>Even if you are careful not to create reference cycles, third-party modules that create a cycle that refers to your object, even indirectly, can trap it in the cycle. For instance, the hypothetical object <i>yourObj</i> in <a name="rf1"></a><a href="0503if1.html">Figure 1</a> gets involved in a cycle, <i>c1-&gt;c2-&gt;c3-&gt;c1</i>, unbeknownst to you. Its reference count can't go to zero until you break the cycle.</p>
<h3>Uncaught Exceptions</h3>

<p>Even if you could be sure that reference cycles don't occur in your program, the uncaught exceptions problem remains. An exception in a function causes the named references at all levels of the function call stack to be retained until the Python interpreter exits, in case you need to explore the data for debugging purposes. Yet, objects that are left over from uncaught exceptions are not guaranteed to be destroyed, as stated in the PLR. See <a name="rl3"></a><a href="#l3">Listing Three</a> for a trick that can help clean up resources (but again, the PLR offers no guarantees).</p>

<p>It should be clear by now that you can't rely on <i>__del__</i> for resource management; for example, RAII does not work in Python, and the <i>del</i> operator is no help in that matter. </p>
<h3>Fighting Indeterminism</h3>

<p><a name="rl4"></a><a href="#l4">Listing Four</a> is C++ code that uses the RAII idiom. The C++ code guarantees that the critical mutex lock resource acquired when instantiating a <i>Lock</i> is released when the function returns, because <i>Lock</i> has a destructor (not shown) that releases it; this is guaranteed by the language standard to be called upon scope exit (that is, function <i>return</i>). The equivalent Python code is only equivalent in appearance: <i>lock</i> is only a named reference to a <i>Lock</i> instance object, so upon scope exit, the reference count of the created <i>Lock</i> is decreased, but:</p>



<ul>
  <li>Python doesn't guarantee that the reference count will be zero, since <i>do_stuff()</i> might have increased it.</li>
  <li>Even if <i>do_stuff()</i> didn't affect the reference count, the <i>lock</i> named reference is not deleted if the scope is being exited due to an exception raised by <i>do_stuff()</i>.</li>
  <li>Even if no exception is raised, Python doesn't guarantee that any special function (<i>__del__</i>, for instance) will be called. </li>
</ul>



<p>Until the next release of Python, the only solution is to make judicious use of the <i>try-finally</i> clause and manually call the release method (<a name="rl5"></a><a href="#l5">Listing Five</a>). This works well, except that the coder of <i>Lock</i> must remember to document which method must be called to release resource (not too bad), but the user must read the documentation and notice it (far less likely). In addition, users must remember to use a <i>try-finally</i> clause. The latter is actually easy to forget or to get wrong (<a name="rl6"></a><a href="#l6">Listing Six</a>). Also, you can't mix <i>except</i> and <i>finally</i> clauses. Rather, a <i>try-except</i> must wrap a <i>try-finally</i>, or vice versa (<a name="rl7"></a><a href="#l7">Listing Seven</a>). This is an unfortunate obfuscation of code that begs for refactoring into a separate function.</p>

<p>Starting with Python 2.4, a new type of expression lets you use the keyword <i>with</i>. This lets you write <a name="rl7"></a><a href="#l7">Listing Seven</a> as <a name="rl8"></a><a href="#l8">Listing Eight</a>. This does the right thing as long as the developer of <i>Lock</i> has defined an <i>__exit__</i> method in <i>Lock</i>. Outside of the <i>with</i> block, the object that <i>lock</i> refers to should not be used. This new syntax cleans things up somewhat but still leaves it up to you to remember that <i>Lock</i> requires proper manual resource management; legacy code will not be able to take advantage of this feature (though adding an <i>__exit__</i> would be easy to do manually). Also, the PEP (PEP310, http:// www.python.org/peps/pep-0310.html) doesn't allow for multiple variables on the <i>with</i> line, though that is likely to be a rare requirement. </p>

<p>In cases where a <i>with</i> block is still not adequate (for instance, if you have more than one object to guard with the <i>with</i> and don't want to nest two <i>with</i> clauses), your only options are to:</p>



<ul>
  <li>Continue with <i>try-finally</i> and <i>try-except</i>. </li>
  <li>Go with something like detscope.py that provides a means of automating the <i>try-finally</i> mechanics (see <a name="rl9"></a><a href="#l9">Listing Nine</a> for a functional prototype that is, however, not multithreadsafe). </li>
  <li>Develop your own technique. </li>
</ul>
<h3>Breaking the Cycle</h3>

<p>Since Python 2.1, the standard weakref module supports the concepts of weak reference. A <i>weakref.ref(yourObject)</i> is an object that does not affect the reference count of <i>yourObject</i>. It has other nice properties, such as being testable for nullness, and letting you specify a callback that gets called when <i>yourObject</i> is destroyed; see <a name="rl10"></a><a href="#l10">Listing Ten</a>. A weak reference can be used to break a reference cycle because it tells the interpreter "Don't keep this object alive on my account." <a name="rl11"></a><a href="#l11">Listing Eleven</a> does not create any cycle.</p>

<p>There is a catch: Reference cycles can be hard to find. Since Python 2.1, a garbage collector has been added that detects cycles and frees as many trapped objects as possible. The garbage collector can destroy an object involved in a cycle only if that object does not have a <i>__del__</i> method. This is simply because a cycle has no beginning and no end, so there is no way of knowing which object's <i>__del__</i> should be called first. Cycles that cannot be destroyed are put in a special list that you can manipulate via the gc module.</p>

<p>The gc module gives access to the garbage collector. The most useful members of gc are:</p>



<ul>
  <li><i>garbage</i>, a list containing all objects with reference count <i>&gt; 1</i> but that your code can no longer reach, and which has a <i>__del__</i> method. </li>
  <li><i>collect()</i>, forces a cleanup to update <i>gc.garbage</i>.</li>
  <li><i>get_referrers(obj)</i>, gets a list of objects that refer to <i>obj</i>.</li>
  <li><i>get_referents(obj)</i>, gets a list of objects referred to by <i>obj</i>.</li>
</ul>



<p><a name="rl12"></a><a href="#l12">Listing Twelve</a> provides code useful for exploring the concept of cycles, and <a name="rl13"></a><a href="#l13">Listing Thirteen</a> is a sample session using it and showing how the cycle is broken. Remember that <i>gc.garbage</i> is a standard Python list so it holds "hard" references to your objects: If you manually break a cycle, you must also remove your object from this list for it to be labeled as "unused" (reference count = 0). (See http://aspn .activestate.com/ASPN/Cookbook/Python/Recipe/65333/ for a recipe to dump unreachable objects using gc.garbage.)</p>

<p>If you're working with versions of Python prior to 2.1, you can use Cyclops (http://www.python.org/ftp/). This package, not in the standard library, contains the cyclops module, which helps identify reference cycles. Contrary to Python's garbage collector, Cyclops seems to require that you tell it which objects to inspect for cycles. </p>

<p>Once you have identified that a cycle is being created, you must figure out how (where) to break the cycle, or, if that is not possible, how to properly free the critical resources being held some other way. Most often, this will involve wrapping an object with a weakref.ref or weakref.proxy. </p>
<h3>Conclusion</h3>

<p>If you use Python for its portability, keep both platform and interpreter portability in mind: You must be careful not to rely on your objects being destroyed, ever, so you can't use the RAII idiom. The <i>del</i> operator affects only whether you can access (reach) an object, not the object's existence. Therefore, you must make sure you read the documentation of a class to see if a special disposal method must be called when you no longer need the object, and use such disposal methods inside a <i>try-finally</i> clause. In Python 2.4, you should be able to use the <i>with</i> clause, but that still requires work on your part. Detscope.py and other techniques may be appropriate as well. Circular references may prevent such a disposal from taking place, in which case you must hunt down the cycles manually or using pdb or gc or Cyclops, and fix them using weak references available via the weakref module.</p>
<h3>Acknowledgments </h3>

<p>Thanks to Holger D&ouml;urer, Todd MacCulloch, Francis Moore, and Pierre Rouleau for their helpful reviews of the drafts of this article.</p>


<p><b>DDJ</b></p>



	
	
<br>
<br>
<b><a name="l1"></a>Listing One</b><br>
<pre>class A:
    def __init__(self):
        self.b = B(self)
    def __del__(self):
        print "goodbye"
class B:
    def __init__(self, a):
        self.a = a
aa = A()
del aa</pre>
<a href="#rl1">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l2"></a>Listing Two</b><br>
<pre>while 1: 
    aa = A()</pre>
<a href="#rl2">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l3"></a>Listing Three</b><br>
<pre># someScript.py
def run_application():
    ...
def handle_exception():
    ...
try:
    run_application()
except: # catch all
    handle_exception()
    # *attempt* to free as many remaining as possible
    import sys
    sys.exc_clear() 
    sys.exc_traceback = None
    sys.last_traceback = None</pre>
<a href="#rl3">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l4"></a>Listing Four</b><br>
<pre># C++ code:
void func() {
    Lock lock;
    do_stuff();
}
# "equivalent" Python code:
def func():
    lock = Lock()
    do_stuff()</pre>
<a href="#rl4">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l5"></a>Listing Five</b><br>
<pre>def func():
    lock = Lock()
    try:
        do_stuff()
    finally:
        lock.release()</pre>
<a href="#rl5">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l6"></a>Listing Six</b><br>
<pre># extreme danger:
open('somefile.txt','w').write(contents)
# runtime error in exception handler:
try:
    ff = open('somefile.txt','w')
    ff.write(contents)
finally:
    ff.close() #bang!! ff undefined
# multithreaded:
ff = open('somefile.txt','w')
# if exception raised before getting
# into the try-finally clause: bang!
try:
    ff.write(contents)
finally:
    ff.close()</pre>
<a href="#rl6">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l7"></a>Listing Seven</b><br>
<pre>def func():
    lock = Lock()
    # unfortunately not allowed:
    # try:
    #     do_stuff()
    # except MyExcept:
    #     undo_stuff()
    # finally:
    #     lock.release()

    # instead, nesting is necessary:
    try:
        try: 
            do_stuff()
        except MyExcept:
            undo_stuff()
    finally:
        lock.release()</pre>
<a href="#rl7">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l8"></a>Listing Eight</b><br>
<pre>def func():
    with lock = Lock():
        do_stuff()</pre>
<a href="#rl8">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l9"></a>Listing Nine</b><br>
<pre># detscope.py
"""
Example use: a function, funcWCriticalRes(), creates two critical resources, 
of type CritRes1 and CritRes2, and you want those resources to be released 
regardless of control flow in function:
  import detscope.py
  def funcWCriticalRes():
      critres1 = CritRes1()
      critres2 = CritRes2()
      use_res(res1, res2)
      if something:
          return # early return
      ...
  funcWCriticalRes = ScopeGuarded(funcWCriticalRes)

  class CritRes1(NeedsFinalization):
      def __init__(self, ...):
          ...
      def _finalize(self):
          ...
  class CritRes2(NeedsFinalization):
      def __init__(self, ...):
          ...
      def _finalize(self):
          ...
"""
import sys
def ScopeGuarded(func):
    return lambda *args, **kwargs: ScopeGuardian(func, *args, **kwargs)
_funcStack = []
class NeedsFinalization:
    def __init__(self):
        print '\n%s: being created' % repr(self)
        self.__finalized = False
        try: _funcStack[-1].append(self)
        except IndexError:
            raise RuntimeError, "Forgot to scope-guard function? "
    def finalizeMaster(self):
        """Derived classes MUST define a self._finalize() method,
        where they do their finalization for scope exit."""
        print '%s: Finalize() being called' % repr(self)
        self._finalize()
        self.__finalized = True
    def __del__(self):
        """This just does some error checking, probably want to remove
        in production in case derived objects involved in cycles."""
        try:
            problem = not self.__finalized
        except AttributeError:
            msg = '%s: NeedsFinalization.__init__ not called for %s' \
                  % (repr(self), self.__class__)
            raise RuntimeError, msg
        if not problem:
            print '%s: Finalized properly' % repr(self)
        else:
            print 'Forgot to scope-guard func?'
def ScopeGuardian(func, *args, **kwargs):
    try:
        scopedObjs = []
        _funcStack.append(scopedObjs)
        func(*args, **kwargs)
    finally:
        _funcStack.pop()
        if scopedObjs != []:
            scopedObjs.reverse() # destroy in reverse order from creation
            for obj in scopedObjs:
                obj.finalizeMaster()</pre>
<a href="#rl9">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l10"></a>Listing Ten</b><br>
<pre>import weakref
class Foo: 
    def __str__(self):
        return "I'm a Foo and I'm ok"
    def __del__(self):
        print "obj %s: I was a Foo and now I'm dead" % id(self)
def noticeDeath(wr):
    print "weakref %s: weakly ref'd obj has died" % id(wr)
yourObj = Foo()
wr = weakref.ref(yourObj, noticeDeath)
print 'weakref %s -&gt; obj %s: %s' % (id(wr), id(wr()), wr())

del yourObj
assert wr() is None
# output: 
#   weakref 17797504 -&gt; obj 17794632: I'm a Foo and I'm ok
#   weakref 17797504: weakly ref'd obj has died
#   obj 17794632: I was a Foo and now I'm dead</pre>
<a href="#rl10">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l11"></a>Listing Eleven</b><br>
<pre>import weakref
class A:
    def __init__(self):
        self.b = B(self)
    def __del__(self):
        print "goodbye"
class B:
    def __init__(self, a):
        self.a = weakref.ref(a)
aa = A()
del aa</pre>
<a href="#rl11">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l12"></a>Listing Twelve</b><br>
<pre># testCycle.py
from sys import getrefcount
import gc
class CycleContainer:
    def __init__(self, instName):
        self.instName = instName
        self.cycle = Cycle(self)
        print "Constructed a CycleContainer named '%s'" % instName
    def refs(self):
        """Get number of references to self. The 3 was 
        determined experimentally, so method returns 
        expected number of references."""
        return getrefcount(self)-3
    def __del__(self):
        """Will prevent CycleContainer instance from being destroyed by gc"""
        print "CycleContainer '%s' being finalized" % self.instName
class Cycle:
    def __init__(self, containerOfSelf):
        self.container = containerOfSelf
def checkgc():
    gc.collect()
    return gc.garbage</pre>
<a href="#rl12">Back to article</a><br>
	
	
	
<br>
<br>
<b><a name="l13"></a>Listing Thirteen</b><br>
<pre>&gt;&gt;&gt; from testCycle import CycleContainer, Cycle, checkgc
&gt;&gt;&gt; aa= CycleContainer('one')
Constructed a CycleContainer named 'one'
&gt;&gt;&gt; aa.refs()
1
&gt;&gt;&gt; aa.cycle = Cycle(aa)
&gt;&gt;&gt; aa.refs()
2
&gt;&gt;&gt; checkgc()
[]
&gt;&gt;&gt; del aa
&gt;&gt;&gt; checkgc()
[&lt;testCycle.CycleContainer instance at 0x00984CB0&gt;]
&gt;&gt;&gt; checkgc()[0].refs()
2
&gt;&gt;&gt; bad = checkgc()[0]
&gt;&gt;&gt; del bad.cycle
&gt;&gt;&gt; bad.refs()
2
&gt;&gt;&gt; checkgc()
[&lt;testCycle.CycleContainer instance at 0x00984CB0&gt;]
&gt;&gt;&gt; del checkgc()[:]
&gt;&gt;&gt; checkgc()
[]
&gt;&gt;&gt; bad.refs()
1
&gt;&gt;&gt; del bad
CycleContainer 'one' being finalized</pre>
<a href="#rl13">Back to article</a><br>
	
	
	


</body>
</html>